title: Voronoi Art Generator
description: An interactive way to generate art using Voronoi diagrams
#show_downloads: true
show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman

# to toggle showing the github link:
#github:
#  is_project_page: false

#website: https://tycho-bear.github.io/voronoi

#site.url: https://tycho-bear.github.io/voronoi

# bundle exec jekyll serve --baseurl=""
# serve with an empty string for the baseurl
# this means that if I use the baseurl in links, everything still works locally,
  # and the github pages deployment should actually be able to use the javascript!
#baseurl: /voronoi
baseurl: /voronoi-art-generator

github:
  is_project_page: true
#  is_project_page: false
