title: Voronoi Art Generator
description: An interactive way to generate art using Voronoi diagrams
#show_downloads: true
show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman

# to toggle showing the github link:
#github:
#  is_project_page: false

# idk what this does
#website: https://tycho-bear.github.io/voronoi-art-generator

# should work for github pages
url: https://tycho-bear.github.io
baseurl: /voronoi-art-generator

# bundle exec jekyll serve --baseurl=""
# serve with an empty string for the baseurl
# this means that if I use the baseurl in links, everything still works locally,
  # and the github pages deployment should actually be able to use the javascript!
#baseurl: /voronoi

#url: https://tycho-bear.github.io/voronoi-art-generator



github:
  is_project_page: true
  repository_name: voronoi-art-generator
  repository_url: https://github.com/tycho-bear/voronoi-art-generator
  owner_name: Tycho Bear
  owner_url: https://github.com/tycho-bear
#  is_project_page: false
